package de.luhmer.owncloudnewsreader.database.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CURRENT_RSS_ITEM_VIEW.
 */
public class CurrentRssItemView {

    private long id;
    private long rssItemId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CurrentRssItemView() {
    }

    public CurrentRssItemView(long id) {
        this.id = id;
    }

    public CurrentRssItemView(long id, long rssItemId) {
        this.id = id;
        this.rssItemId = rssItemId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getRssItemId() {
        return rssItemId;
    }

    public void setRssItemId(long rssItemId) {
        this.rssItemId = rssItemId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
