# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(
      task: "clean assemble",
      flavor: "oss",
      build_type: "Release",
      properties: {
          "android.injected.signing.store.file" => "",
          "android.injected.signing.store.password" => "",
          "android.injected.signing.key.alias" => "",
          "android.injected.signing.key.password" => "",
      }
    )
    upload_to_play_store(
        track: 'beta',
        release_status: 'draft',
        mapping: './News-Android-App/build/outputs/mapping/ossRelease/mapping.txt'
    )
  end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end
end
