/*
 * Android ownCloud News
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU AFFERO GENERAL PUBLIC LICENSE for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this library.  If not, see <http://www.gnu.org/licenses/>.
 */

package de.luhmer.owncloudnewsreader.model;

import androidx.annotation.Nullable;

/**
 * Client-only state attached to a single RSS item that is <b>not</b> backed by the Nextcloud News
 * server. It is kept separate from {@link de.luhmer.owncloudnewsreader.database.model.RssItem}
 * (which is generated by greenDAO and refreshed on every sync) and looked up by item id via
 * {@link de.luhmer.owncloudnewsreader.repository.ClientItemStateRepository}.
 * <p>
 * Currently this holds the full text extracted from the original website. Other client-side data
 * that has no server counterpart (e.g. podcast playback progress) can be added here later.
 */
public class ClientItemState {

    /** Full text extracted from the original website, or null if it has not been fetched yet. */
    @Nullable private String fullTextHtml;

    /** Whether the webview should currently render the extracted full text instead of the feed content. */
    private boolean showingFullText;

    /** Whether a full-text fetch is currently in flight for this item. Owned by the running
     *  {@link de.luhmer.owncloudnewsreader.async_tasks.FetchFullTextTask}; lives here (rather than on a
     *  fragment) so concurrent fetches for the same item are deduped across fragment recreation. */
    private boolean fetchingFullText;

    @Nullable
    public String getFullTextHtml() {
        return fullTextHtml;
    }

    public void setFullTextHtml(@Nullable String fullTextHtml) {
        this.fullTextHtml = fullTextHtml;
    }

    /** @return true once full text has been fetched and cached for this item */
    public boolean hasFullText() {
        return fullTextHtml != null && !fullTextHtml.isEmpty();
    }

    public boolean isShowingFullText() {
        return showingFullText;
    }

    public void setShowingFullText(boolean showingFullText) {
        this.showingFullText = showingFullText;
    }

    public boolean isFetchingFullText() {
        return fetchingFullText;
    }

    public void setFetchingFullText(boolean fetchingFullText) {
        this.fetchingFullText = fetchingFullText;
    }
}
