# synced from @nextcloud/android-config
name: "Validate Gradle Wrapper"
on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency: 
  group: validate-gradle-wrapper-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    validation:
        name: "Validation"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2 # v2.1.1
